sudo: required
dist: trusty
language: cpp

compiler:
    - gcc

before_install:
    - sudo add-apt-repository -y ppa:beineri/opt-qt571-trusty
    - sudo add-apt-repository -y ppa:adrozdoff/cmake
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get -qy update

install:
    - sudo apt-get -qy --only-upgrade install cmake
    - sudo apt-get -qy install qt57base qt57tools
    - sudo apt-get -qy install gcc-5 g++-5

script:
    - export CXX=g++-5
    - export CC=gcc-5
    - cmake -DCMAKE_PREFIX_PATH=/opt/qt57/lib/cmake .
    - make VERBOSE=1

os:
- linux
